### ISSUE TITLE
update deps please

### ISSUE THREAD

**Issue by chrisdlangton** [jordanpotti/CloudScraper#6]
python --version `Python 2.7.15`

pip install bs4
```
Collecting bs4
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting beautifulsoup4 (from bs4)
  Downloading https://files.pythonhosted.org/packages/f8/c7/741c97d7366f4779ca73d244904978b43a81fd37d85fcf05ad19d472c1ce/beautifulsoup4-4.6.3-py2-none-any.whl (90kB)
Installing collected packages: beautifulsoup4, bs4
  Running setup.py install for bs4 ... done
Successfully installed beautifulsoup4-4.6.3 bs4-0.0.1
```
python CloudScraper/CloudScraper.py -l ./js_files_url_list.txt
```
Description:
        CloudScraper is a tool to search through the source code of websites in order to find cloud resources belonging to a target.
        by Jordan Potti
        @ok_bye_now

('Beginning search for cloud resources in ', 'http://s3.amazonaws.com/%20new.redacted.com/file.js\n', '\n')
Traceback (most recent call last):
  File "CloudScraper/CloudScraper.py", line 129, in <module>
    main()
  File "CloudScraper/CloudScraper.py", line 121, in main
    start(line, arguments.depth)
  File "CloudScraper/CloudScraper.py", line 32, in start
    soup = BeautifulSoup(start_page.text, "lxml")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```
tried `pip install lxml` and it was solved for me

**Comment by jordanpotti** [comment]
Tool is written for Python 3.6. 

Thanks for letting me and others know about this issue though!
