### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by jaikishantulswani** [jordanpotti/CloudScraper#7]
Hi @jordanpotti ,
CloudScraper works fine when we supply a single domain but gives error when we try to extract links from list of hosts using -l flag.

`
HTTPConnectionPool(host='example.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb4430c8c>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "CloudScraper.py", line 129, in <module>
    main()
  File "CloudScraper.py", line 119, in main
    start(line_mod.rstrip(), arguments.depth)
  File "CloudScraper.py", line 32, in start
    soup = BeautifulSoup(start_page.text, "lxml")
UnboundLocalError: local variable 'start_page' referenced before assignment
`

**Comment by mrthankyou** [comment]
This occurs when a single domain is supplied.
